apis/urls.py
from django.urls import path

from . import views

app_name = 'apis'
urlpatterns = [
    path('', views.run_by_post, name='run_by_post'),
    path('run_brand', views.run_brand_by_post, name='run_brand_by_post'),
    path('run_brand_no_capture', views.run_brand_by_post_no_capture, name='run_brand_by_post_no_capture'),
    path('run_brand_all_logs', views.run_brand_all_logs_by_post, name='run_brand_all_logs_by_post'),
    path('seoanalytics', views.seo_by_post, name='seo_by_post'),
    path('argosubmitter', views.argosubmitter_by_post, name='argosubmitter_by_post'),
    path('podlog', views.podlog_by_post, name='podlog_by_post'),
    path('uploadconversions', views.conversions_by_post, name='conversions_by_post'),
    path('upconverftd', views.conversions_by_post_ftd, name='conversions_by_post_ftd'),
    path('upconverqftd', views.conversions_by_post_qftd, name='conversions_by_post_qftd'),
    path('upconversignup', views.conversions_by_post_signup, name='conversions_by_post_signup'),
    path('upconverqftdnaiveroas', views.conversions_by_post_qftdnaiveroas, name='conversions_by_post_qftdnaiveroas'),
    path('test_automate', views.test_automate, name='test_automate'),
    path('abtest_snapshot', views.abtest_snapshot, name='abtest_snapshot'),
    path('run_data_collector', views.run_data_collector_by_post, name='run_data_collector_by_post'),
    # path('api/br/<int:brand_id>', views.run_by_post, name="brand_run_by_post"),
    # path('runwatch/<str:job_details>', views.runwatch, name='runwatch')
]

brands/urls.py
from django.urls import path

from . import views

app_name = 'brands'
urlpatterns = [
    path('', views.index, name='index'),
    path('running_processes/', views.running_processes, name='running_processes'),
    path('cron_jobs/', views.cron_jobs, name='cron_jobs'),
    path('last_legend_log/', views.last_legend_log, name='last_legend_log'),
    path('last_8_log/', views.last_8_log, name='last_8_log'),
    path('last_mtd_log/', views.last_mtd_log, name='last_mtd_log'),
    path('last_prev_log/', views.last_prev_log, name='last_prev_log'),
    path('last_8_full_log/', views.last_8_full_log, name='last_8_full_log'),
    path('last_mtd_full_log/', views.last_mtd_full_log, name='last_mtd_full_log'),
    path('last_prev_full_log/', views.last_prev_full_log, name='last_prev_full_log'),
    path('last_saas_log/', views.last_saas_log, name='last_saas_log'),
    path('last_data_collector_log/', views.last_data_collector_log, name='last_data_collector_log'),
    path('brand_searcher/', views.brand_searcher, name='brand_searcher'),
    path('<str:brand_grouping_name>/', views.subbrands, name='subbrands'),
    path('runwatch/<str:job_details>', views.runwatch, name='runwatch'),
]

# https://levelup.gitconnected.com/from-html-to-django-6d8344da11d6

django_wrapper/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('brands/', include('brands.urls')),
    path('apis/', include('apis.urls')),

]

brands/models.py
from django.db import models

# Create your models here.
class Brand_Details(models.Model):
    class Meta:
        app_label = 'brands'
        db_table = 'brand_details_full'

    # use_qftd_as_ftd = models.SmallIntegerField(null=True, default=0)
    # token = models.CharField(max_length=70, null=True)
    # subbrandid = models.CharField(max_length=45, null=True)
    # report_kind = models.CharField(max_length=20, choices=Report_Types.choices, null=True)
    # prefixed_player_id = models.CharField(max_length=100, null=True)
    passwd_valid = models.SmallIntegerField(null=True, default=0)
    id = models.BigIntegerField(primary_key=True)
    # deal_kind = models.CharField(max_length=20, choices=Deal_Types.choices, null=True, default=Deal_Types.date_based)
    # days_chunk = models.IntegerField(null=True, default=0)
    # clk_alias = models.CharField(max_length=45, null=True)
    brand_group_details_id = models.IntegerField(default=-1, null=True)
    brand_display_name = models.CharField(max_length=45, null=True)
    brand_grouping_id = models.CharField(max_length=45, null=True)
    backend_interface_group= models.CharField(max_length=45, null=True)
    brand_id = models.BigIntegerField(default=-1, null=True)
    # backend_interface_group = models.CharField(max_length=45, null=True)
    # Modified = models.DateTimeField(null=True)
    # Gdrive_Folder = models.CharField(max_length=256, null=True)

    # def __str__(self):
    #     return self.brand_display_name

class Brand_Grouping(models.Model):
    class Meta:
        app_label = 'brands'
        db_table = 'brand_group_details'

    # use_qftd_as_ftd = models.SmallIntegerField(null=True, default=0)
    # token = models.CharField(max_length=70, null=True)
    # subbrandid = models.CharField(max_length=45, null=True)
    # report_kind = models.CharField(max_length=20, choices=Report_Types.choices, null=True)
    # prefixed_player_id = models.CharField(max_length=100, null=True)
    # passwd_valid = models.SmallIntegerField(null=True, default=0)
    id = models.BigIntegerField(primary_key=True)
    # deal_kind = models.CharField(max_length=20, choices=Deal_Types.choices, null=True, default=Deal_Types.date_based)
    # days_chunk = models.IntegerField(null=True, default=0)
    # clk_alias = models.CharField(max_length=45, null=True)
    brand_grouping_name = models.CharField(max_length=45, null=True)
    backend_interface = models.CharField(max_length=45, null=True)
    # brand_display_name = models.CharField(max_length=45, null=True)
    # brand_id = models.BigIntegerField(default=-1, null=True)
    # backend_interface_group = models.CharField(max_length=45, null=True)
    # Modified = models.DateTimeField(null=True)
    # Gdrive_Folder = models.CharField(max_length=256, null=True)

    def __str__(self):
        return self.brand_grouping_name

brands/forms.py
from django import forms

class NameForm(forms.Form):
    searched = forms.CharField(label='Requested string to look for', max_length=100)

brands/views.py
import datetime
from datetime import timezone
import stat
import sys
import time
import os
import subprocess
import traceback

from django.shortcuts import get_object_or_404,render,HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Brand_Details
from .models import Brand_Grouping
from .utils import *
from .mtd_log_utils import *
import psutil
from django.shortcuts import render
from .forms import NameForm


def index(request):
    template_name = 'brands/index.html'
    context_object_name = 'brand_details_list'
    brands_list = get_br_grp_list()
    brands_list = insert_letters_as_separator(brands_list)
    brands_list.append("$")
    brands_list.append("running_processes")
    brands_list.append("cron_jobs")
    brands_list.append("last_legend_log")
    brands_list.append("last_8_log")
    brands_list.append("last_mtd_log")
    brands_list.append("last_prev_log")
    brands_list.append("last_saas_log")
    brands_list.append("last_data_collector_log")
    brands_list.append("last_8_full_log")
    brands_list.append("last_mtd_full_log")
    brands_list.append("last_prev_full_log")
    brands_list.insert(0," ")
    brands_list.insert(0,"brand_searcher")
    # print(brands_list[0])
    return render(request, 'brands/index.html', {'brand_details_list': brands_list})

def run_by_post(request):
    if request.method=="POST":
        cmd = build_post_cmd(request, request.POST)
        if cmd is None:
            brand_grouping_name = "XXX"
            print(">>>>>>>>>>>>>>>> CMD WAS NONE ???????")
            return render(request, 'brands/subbrands.html', {'brand_grouping_name':brand_grouping_name, 'form': request.POST})
        print(f"Going Into remote command {cmd} ______________ on {os.getcwd()} {datetime.datetime.now()}")
        job_details = cmd
        return HttpResponseRedirect(reverse('brands:runwatch_api', args=(job_details,)))
    return None

def subbrands(request, brand_grouping_name):
    d_enddate = datetime.datetime.now() # "2018-06-12T00:00"
    d_startdate = d_enddate - datetime.timedelta(days=7)
    enddate = f"{d_enddate.date()}T00:00"
    startdate = f"{d_startdate.date()}T00:00"
    dynoid=''
    heroku_app = ''
    if request.method=="POST":
        cmd = build_cmd(request, request.POST, brand_grouping_name)
        if cmd is None:
            print(">>>>>>>>>>>>>>>> CMD WAS NONE ???????")
            return render(request, 'brands/subbrands.html', {'brand_grouping_name':brand_grouping_name, 'form': request.POST})
        # print(f"Going Into remote command {cmd} ______________ on {os.getcwd()} {datetime.datetime.now()}")
        # cs = run_remote_command(cmd)
        # print("WE ARE AFTER REMOTE_COMMAND cs=",cs)
        # print(cs.output)
        # print("going to job details......* * * *  **  *  ** ** ")
        job_details = cmd
        return HttpResponseRedirect(reverse('brands:runwatch', args=(job_details,)))
    subbrands_list = get_dosubs_list(brand_grouping_name)
    # print(">>>>>>>>>>>>>>>>> SUBSSUBS",subbrands_list)
    return render(request, 'brands/subbrands.html', {'group_name': brand_grouping_name, 'subbrands_list': subbrands_list, 'startdate':startdate, 'enddate':enddate})


def runwatch(request,job_details):
    cmd = job_details
    cs = run_remote_command(cmd)
    # cs = refresh_output(job_details)
    # (dynoid,hap) = job_details.split("__")
    # print(f"We are in runwatch....request={request} request_POST={request.POST} jobdetails={job_details}")
    csout = cs.stdout.split('\n')
    cserr = cs.stderr.split('\n')
    # if 'DBG_JS_DBS' in os.environ.keys():
    #     cserr.append(f"DBS =+= {os.environ['DBG_JS_DBS']} =+=")
    if len(csout)>2:
        # print("len biger than 0","***",csout[-1])
        # print("LAST LINE err",cserr[-2],"LAST LINE out",csout[-2])
        if csout[-1]=='': del csout[-1]
        if "State changed from up to complete" in csout[-1]:
            csout.append(" --- ")
            csout.append(" ----- ")
            csout.append("THIS JOB IS DONE.")
        if "State changed from up to complete" in cserr:
            cserr.append(" -E- ")
            cserr.append(" --E-- ")
            cserr.append("THIS JOB IS DONE.")
    # return HttpResponseRedirect(reverse('brands:index'))
    return render(request,'brands/finalresult.html',{'job_details':job_details,'csout':csout,'cserr':cserr})

def brand_searcher(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # print("form valid , what next?")
            # print("form = ",form.cleaned_data)
            searched = request.POST['searched']
            queried_brand_details = {}
            for e in Brand_Details.objects.all().using('brands'):
                # print("POST", e.brand_id, e.brand_display_name)
                srch = searched.lower()
                if srch in e.brand_display_name.lower() or srch in str(e.brand_id).lower() \
                        or srch in e.brand_grouping_id.lower() or srch in e.backend_interface_group.lower():
                    queried_brand_details[e.brand_grouping_id] = [e.brand_id, e.brand_display_name,
                                                                  e.brand_group_details_id,
                                                                  e.brand_grouping_id, e.backend_interface_group]
            # queried_brand_details = query with searched ( hint Brand_Details.objects.filter(brand_display_name__contains='searched' )
            return render(request, 'brands/brand_search_result.html',
                          {'searched': searched, 'queried_brand_details': queried_brand_details})
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()
    return render(request, 'brands/search_form.html', {'form': form})

def runwatch_api(request,job_details):
    cmd = job_details
    return render(request,'brands/finalresult.html',{'job_details':'job_details','csout':"THIS IS CSOUT",'cserr':'THIS IS CSERR'})

    cs = run_remote_command(cmd)
    # cs = refresh_output(job_details)
    # (dynoid,hap) = job_details.split("__")
    # print("We are in runwatch....")
    csout = cs.stdout.split('\n')
    cserr = cs.stderr.split('\n')
    # if 'DBG_JS_DBS' in os.environ.keys():
    #     cserr.append(f"DBS =+= {os.environ['DBG_JS_DBS']} =+=")
    return render(request,'brands/finalresult.html',{'job_details':'job_details','csout':csout,'cserr':cserr})
    if len(csout)>2:
        # print("len biger than 0","***",csout[-1])
        # print("LAST LINE err",cserr[-2],"LAST LINE out",csout[-2])
        if csout[-1]=='': del csout[-1]
        if "State changed from up to complete" in csout[-1]:
            csout.append(" --- ")
            csout.append(" ----- ")
            csout.append("THIS JOB IS DONE.")
        if "State changed from up to complete" in cserr:
            cserr.append(" -E- ")
            cserr.append(" --E-- ")
            cserr.append("THIS JOB IS DONE.")
    # return HttpResponseRedirect(reverse('brands:index'))
    return render(request,'brands/finalresult.html',{'job_details':'job_details','csout':csout,'cserr':cserr})

def results(request, brand_grouping_name):
    run_message = f"""{get_heroku_exe()} run:detached doherokupython run -a biz-report {brand_grouping_name}.py  --mtd """
    return render(request, 'brands/results.html', {'running_command': run_message})

def running_processes(request):
    pids = []
    PROCNAMES = ["python3"]
    EXCLUDE_PROCNAMES = ["networkd-dispatcher", "unattended-upgrades", "manage.py"]
    for proc in psutil.process_iter():
        pInfoDict = proc.as_dict()
        excludeit = False
        for exc in EXCLUDE_PROCNAMES:
            if exc in pInfoDict['cmdline']: excludeit = True
        if excludeit: continue
        for PROCNAME in PROCNAMES:
            if os.path.basename(__file__) in pInfoDict['cmdline']: continue
            # if "run.py" not in pInfoDict['cmdline']: continue
            if PROCNAME in proc.name():
                # print(f"{pInfoDict['username']},ppid={pInfoDict['ppid']}, pid={pInfoDict['pid']},{pInfoDict['status']}\n{pInfoDict['cmdline']}\n\n")
                pids.append(f"pid={pInfoDict['pid']} {str(pInfoDict['cmdline'])}")
    if len(pids)>0:
        pids.append("--")
        pids.append("--")
        pids.append(f"Updated on {datetime.datetime.now()}")
        touch_file(f"{os.environ['AUTO_RUNS_FOLDER']}{os.sep}running_processes.usedon")
    return render(request, 'brands/running_processes.html', {'pids': pids})

def cron_jobs(request):
    # print("cron_jobs", request , *request)
    cronlines = []
    cmd = ['crontab','-l']
    cs = subprocess.run(cmd, shell=False, check=True, timeout=1200, capture_output=True,
                        universal_newlines=True)  # , stdout=subprocess.PIPE ,    print(end='')
    for oneline in cs.stdout.split("\n"):
        oneline = oneline.strip()
        if "dom mon dow" in oneline: cronlines.append(f"{oneline}________________# (now time: {datetime.datetime.now()}")
        elif not oneline.startswith("#") : cronlines.append(oneline)
    return render(request, 'brands/cron_jobs.html', {'cronlines': cronlines})

def last_legend_log(request):
    # print("last_log_mtd", request , *request)
    ignored = []  #  get_ignored_terms()
    fn=is_it_newest(folder=os.environ['RUN_LEGEND_FOLDER'])
    loglines = ''
    if fn is not None:
        loglines = show_log(fn=fn, ignored=ignored)
    loglines.append("--")
    loglines.append("--")
    crontab_lines = get_crontab_lines(forwhat="last_legend_cron")

brands/templates/brands/brand_search_result.html
<!DOCTYPE html>
<html>
<body>

{% block content %}
	<center>
	{% if searched %}
		<h1> you searched for {{ searched }}</h1><br/>
		{% for key,values in queried_brand_details.items %}
			<a href="{% url 'brands:subbrands' key %}">{{ key }}</a><br/><br/>
		{% endfor %}
	{% else %}
		<h1> actually no search term? </h1>
	{% endif %}


	</center>
{% endblock %}

<br><br>
<a href="/brands">Go back to brands?</a>
<br><br>
<a href="/brands/brand_searcher">Go back to brand searcher?</a>

</body>
</html>

brands/templates/brands/cron_jobs.html
<!DOCTYPE html>
<html>
<body>
<title> CRONJOBS </title>
<h2> Below cronjobs are scheduled currently.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in cronlines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/finalresult.html
<!DOCTYPE html>
<html>
<body>

<h2> Your job  ={{job_details}}=  has run on the server.<br>
    Below results of it.
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>
<a href="/brands/brand_searcher/">Go back to brand_searcher?</a><br><br>

    {% for oneline in cserr %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>
    {% for oneline in csout %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>
    <br>


<a href="/brands">Go back to brands?</a><br><br>
<a href="/brands/brand_searcher/">Go back to brand_searcher?</a><br><br>

</body>
</html>

brands/templates/brands/index.html
<html>
  <head>
    <title> Brands </title>
    <style>
      ul {
        columns: 4;
        -webkit-columns: 6;
        -moz-columns: 4;
      }
    </style>
  </head>
  <body>

{% if brand_details_list %}
    <div><ul display="grid" class="columns" data-columns="4">
    {% for brand_grouping_name in brand_details_list %}
        {% if brand_grouping_name|length > 1 %}
           <li><a href="{% url 'brands:subbrands' brand_grouping_name %}">{{ brand_grouping_name }}</a></li>
        {% else %}
            <li><h5>{{ brand_grouping_name }}</h5></li>
        {% endif %}
    {% endfor %}
    </ul></div>
{% else %}
    <p>No brands are available.</p>
{% endif %}
    </body>
</html>

brands/templates/brands/last_8_log.html
<!DOCTYPE html>
<html>
<body>
<title> 8 CLKBASEDLIST log</title>
<h2> This is last 8 log filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/last_data_collector_log.html
<!DOCTYPE html>
<html>
<body>
<title> DATA COLLECTION Last log </title>
<h2> This is last data collection log filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/last_legend_log.html
<!DOCTYPE html>
<html>
<body>
<title> LEGEND log</title>
<h2> This is last legend log filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/last_mtd_log.html
<!DOCTYPE html>
<html>
<body>
<title> MTD log </title>
<h2> This is last mtd log filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/last_prev_log.html
<!DOCTYPE html>
<html>
<body>
<title> PREV_MONTH Last log </title>
<h2> This is last prev log filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/last_saas_log.html
<!DOCTYPE html>
<html>
<body>
<title> SAAS log</title>
<h2> This is last saas filtered.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in loglines %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/running_processes.html
<!DOCTYPE html>
<html>
<body>

<h2> Below processes are running currently.<br>
</h2><br>
<a href="/brands">Go back to brands?</a><br><br>

    {% for oneline in pids %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/runwatch.html
<!DOCTYPE html>
<html>
<body>

<meta http-equiv="refresh" content="10" >

<h2> Your job is now running on the server.<br>
    You can click on go back to brands at any time if you dont want to wait for result of this job<br>
    This window will refresh when job done<br>
    When job done you can then close the window at your convenience and get back to brands menu from the link below
</h2>

<form action="" target="_self" method="POST"> {% csrf_token %}
    {% for oneline in cserr %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>
    {% for oneline in csout %}
        <label>{{oneline}}</label><br>
    {% endfor %}
    <br>
    <br>
  <input type="submit" value="Refresh">
</form>

<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/search_form.html
<!DOCTYPE html>
<html>
<body>

<h2> Brand Searcher ( any string will do ) ( dispname,groupname,backend , even brand_id ... well mostly ;-) ) </h2>

<form action="" target="_self" method="POST"> {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>


<br><br>
<br><br>
<a href="/brands">Go back to brands?</a>

</body>
</html>

brands/templates/brands/subbrands.html
<!DOCTYPE html>
<html>
<body>

<h2> Run Info Collector for  ***    {{ group_name }}  ***        </h2>

<form action="" target="_self" method="POST"> {% csrf_token %}

    <fieldset>
        <legend>Dates Chooser ( hour/minute inputs will be ignored . On Firefox, use pattern YYYY-mm-dd ) </legend>
          <label for="StartDate">Start date:</label>
          <input type="datetime-local" id="StartDate" name="StartDate" pattern="[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}" value={{ startdate }}>
        <label>______</label>
          <label for="EndDate">End date:</label>
          <input type="datetime-local" id="EndDate" name="EndDate" pattern="[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}" value={{ enddate }}>
    </fieldset>
<br><br>


 <br>
  <fieldset>
    <legend>Subbrands Chooser[Default=All]:</legend>
      {% for onesub in subbrands_list  %}
        <input type="checkbox" id="onesub{{ forloop.counter }}" name="{{onesub}}" value="{{ onesub.id }}">
        <label for="onesub{{ forloop.counter }}">{{ onesub }}</label><br>
      {% endfor %}
    </fieldset>
    <br>

  <fieldset>
    <legend>Reports Kind Chooser:</legend>
  <input type="checkbox" id="backend_data" name="backend_data" value="backend_data_value" checked>
  <label for="backend_data">BK________Will pull Backend Info (qck+players+earnings) </label><br>
  <input type="checkbox" id="business_reporting" name="business_reporting" value="business_reporting_value" checked>
  <label for="business_reporting"> BR________Will push to Business_Reporting </label><br>
  <input type="checkbox" id="gaming" name="gaming" value="gaming_value" checked>
  <label for="gaming">GM________Will update new_gaming_partners_data table </label><br>
  </fieldset>
    <br>
  <fieldset>
    <legend>Please DO NOT USE:</legend>
    <input type="text" id="moreswitches" name="moreswitches" value="" maxlength="80" size="80">
  </fieldset>

<br><br><br>
  <input type="submit" value="Press to Run">
</form>


<br><br>
<a href="/brands">Go back to brands list?</a>
<br><br>
<a href="/brands/brand_searcher">Go back to brands search?</a>

</body>
</html>